language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    
services:
  - memcached
  - redis-server
  - mysql
 
before_install:
  - phpenv config-rm xdebug.ini || true
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - printf "\n" | pecl install -f redis
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE homestead;'
  #- mysql -e "CREATE USER 'homestead'@'localhost' IDENTIFIED WITH mysql_native_password AS 'secret';GRANT ALL PRIVILEGES ON *.* TO 'homestead'@'localhost' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;"
  
before_script:
  - cp .env.example .env
  - composer install --no-interaction
  - composer dump-autoload
  - php artisan key:generate
  - php artisan vendor:publish --provider="Spatie\QueryBuilder\QueryBuilderServiceProvider" --tag="config"
  - php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"
  #- php artisan migrate
  - php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="config"
  - php artisan vendor:publish --provider="Spatie\HttpLogger\HttpLoggerServiceProvider" --tag="config"

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
